import { createAuthClient } from "better-auth/react";
import { multiSessionClient } from "better-auth/client/plugins";

// eslint-disable-next-line @typescript-eslint/no-explicit-any
const _authClient: any = createAuthClient({
  baseURL: typeof window !== "undefined" ? window.location.origin : "",
  plugins: [multiSessionClient()],
});

export const authClient: {
  sendVerificationEmail: (options: { email: string; callbackURL?: string }) => Promise<unknown>;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  [key: string]: any;
} = _authClient;

export const {
  signIn,
  signUp,
  signOut,
  useSession,
  resetPassword,
} = _authClient;

// forgetPassword is dynamically generated by Better Auth from the server API
// definition but doesn't appear in static client types.
export const forgetPassword = _authClient.forgetPassword as (options: {
  email: string;
  redirectTo?: string;
}) => Promise<unknown>;
